# Pillars 1-13. Each: metadata for PART 1 + vocab pools that drive title generation.
P = [
dict(n=1, title="Digital Marketing Strategy Foundations", slug="digital-marketing-strategy",
 desc="The parent hub defining how modern digital marketing strategy is planned, budgeted, sequenced and measured across owned, earned and paid channels.",
 intent="Informational → Commercial investigation",
 aud="Founders, marketing managers, agency strategists",
 seo="Owns the head term 'digital marketing strategy' and its planning/framework long-tail.",
 aeo="Answers definitional and 'how do I build' questions with concise, extractable steps.",
 geo="Original planning frameworks and budget benchmarks are highly citable by generative engines.",
 aio="Positions AI as a strategy co-pilot: AI-assisted planning, forecasting and channel mix modelling.",
 sub=["Channel mix modelling","Marketing budget allocation","Goal setting and OKRs","Customer journey mapping","Competitive positioning","Marketing roadmaps","Attribution basics","Strategy audits"],
 kw="digital marketing strategy", kw2=["marketing plan","channel strategy","marketing roadmap","go-to-market"],
 comm="Strategy consulting, platform trials, agency retainers", info="Frameworks, definitions, planning guides",
 cmp="In-house vs agency, channel vs channel", how="Build a plan, run an audit, set budgets", faq="Cost, timeline, team size, first steps",
 topics=["channel mix","marketing budget","customer journey map","marketing roadmap","quarterly planning","competitive positioning","brand messaging","marketing OKRs","attribution model","funnel design","buyer persona","value proposition","go-to-market plan","growth loop","marketing audit","campaign calendar","media plan","North Star metric","demand generation","full-funnel strategy"],
 tools=["HubSpot","Notion","Google Analytics 4","Looker Studio","Airtable","Asana"]),

dict(n=2, title="SEO Fundamentals and Search Strategy", slug="seo-fundamentals",
 desc="Core SEO hub covering how search works, how rankings are earned, and how a sustainable organic strategy is structured.",
 intent="Informational",
 aud="Marketers new to SEO, business owners, content leads",
 seo="Captures the 'what is SEO / how SEO works' head and mid-tail.",
 aeo="Definition and mechanism questions ideal for snippets and voice answers.",
 geo="Clear entity definitions (crawling, indexing, ranking) are reliably cited by AI engines.",
 aio="Explains how AI search changes classic SEO assumptions.",
 sub=["How search engines work","Crawling and indexing","Ranking factors","Search intent","SERP features","White hat vs black hat","SEO roadmaps","Measuring SEO success"],
 kw="SEO basics", kw2=["how search engines work","search intent","ranking factors","organic traffic"],
 comm="SEO tool trials, audits, training courses", info="Mechanics, glossaries, beginner guides",
 cmp="SEO vs PPC, SEO vs social", how="Start SEO, run first audit, fix indexing", faq="Timeframes, costs, DIY vs hire",
 topics=["crawling and indexing","search intent","ranking factors","SERP features","featured snippets","organic traffic","keyword cannibalisation","search console setup","robots.txt","XML sitemaps","canonical tags","index bloat","E-E-A-T","topical authority","semantic search","query deserves freshness","people also ask","zero-click search","SERP volatility","core updates"],
 tools=["Google Search Console","Ahrefs","Semrush","Screaming Frog","Bing Webmaster Tools"]),

dict(n=3, title="Technical SEO and Site Architecture", slug="technical-seo",
 desc="Everything that makes a site crawlable, indexable, fast and structurally sound for search and AI crawlers.",
 intent="Informational → Transactional (tooling)",
 aud="Developers, technical SEOs, site owners",
 seo="Targets high-value technical long-tail with low competition and strong intent.",
 aeo="Diagnostic 'why is my page not indexed' questions produce direct answers.",
 geo="Specification-grade explanations (status codes, schema, rendering) are strong citation candidates.",
 aio="Covers AI crawler access, llms.txt and render budgets for AI systems.",
 sub=["Core Web Vitals","JavaScript SEO","Structured data","Log file analysis","Crawl budget","Site speed","Hreflang","Redirects and status codes"],
 kw="technical SEO", kw2=["Core Web Vitals","structured data","crawl budget","JavaScript SEO"],
 comm="Crawler licences, CDN, monitoring tools", info="Specs, diagnostics, reference guides",
 cmp="CSR vs SSR, crawler vs crawler", how="Fix indexing, improve LCP, add schema", faq="Why not indexed, how fast is fast enough",
 topics=["Core Web Vitals","Largest Contentful Paint","Cumulative Layout Shift","Interaction to Next Paint","JavaScript rendering","server-side rendering","structured data markup","schema.org types","log file analysis","crawl budget","hreflang","301 redirects","soft 404s","pagination","faceted navigation","site architecture","internal link graph","image optimisation","lazy loading","llms.txt","AI crawler access","edge caching","HTTP status codes","mobile-first indexing"],
 tools=["Screaming Frog","Lighthouse","PageSpeed Insights","Cloudflare","Sitebulb","Google Search Console"]),

dict(n=4, title="On-Page SEO and Content Optimization", slug="on-page-seo",
 desc="How individual pages are structured, written and marked up to rank and to be quoted by answer engines.",
 intent="Informational → How-to",
 aud="Content writers, SEO specialists, bloggers",
 seo="Dense mid-tail around titles, headings, meta and content structure.",
 aeo="Directly serves 'how do I optimise X' queries.",
 geo="Passage-level structuring guidance is itself the thing generative engines reward.",
 aio="AI-assisted drafting, optimisation and entity coverage.",
 sub=["Title tags","Meta descriptions","Header hierarchy","Internal linking","Image SEO","Content structure","Entity coverage","Readability"],
 kw="on-page SEO", kw2=["title tag optimisation","meta description","internal linking","content optimisation"],
 comm="Optimisation tools, content graders", info="Element-by-element guides",
 cmp="Long vs short form, tool vs tool", how="Optimise a post, write a title, build internal links", faq="Ideal length, keyword density",
 topics=["title tags","meta descriptions","H1 hierarchy","internal linking","anchor text","image alt text","URL structure","content depth","entity coverage","semantic HTML","table of contents","FAQ schema","readability score","keyword placement","content refresh","snippet optimisation","passage ranking","content pruning","orphan pages","topic clusters"],
 tools=["Surfer SEO","Clearscope","Yoast","RankMath","Frase"]),

dict(n=5, title="Keyword Research and Search Demand Analysis", slug="keyword-research",
 desc="Finding, sizing, clustering and prioritising the queries a business should compete for.",
 intent="Informational → Commercial investigation",
 aud="SEO analysts, content strategists, PPC managers",
 seo="Owns research methodology and tool-comparison traffic.",
 aeo="'How do I find keywords for X' answers cleanly.",
 geo="Clustering methodologies and difficulty formulas are citable frameworks.",
 aio="AI-driven clustering, intent classification and gap analysis.",
 sub=["Search volume","Keyword difficulty","Intent classification","Keyword clustering","Long-tail discovery","Competitor gaps","Seasonality","Prioritisation models"],
 kw="keyword research", kw2=["long-tail keywords","keyword difficulty","search volume","keyword clustering"],
 comm="Keyword tool subscriptions", info="Methodology, metrics explained",
 cmp="Ahrefs vs Semrush, free vs paid", how="Build a keyword map, cluster at scale", faq="How many keywords, which metric matters",
 topics=["search volume","keyword difficulty","search intent classification","keyword clustering","long-tail keywords","competitor keyword gaps","seasonal keywords","branded vs non-branded","zero-volume keywords","question keywords","keyword mapping","SERP analysis","topical gap analysis","share of voice","keyword cannibalisation","priority scoring","local keyword research","multilingual keywords"],
 tools=["Ahrefs","Semrush","Google Keyword Planner","AlsoAsked","Keyword Insights"]),

dict(n=6, title="Content Marketing and Editorial Operations", slug="content-marketing",
 desc="Planning, producing, distributing and maintaining content as a compounding business asset.",
 intent="Informational → Commercial",
 aud="Content managers, editors, marketing teams",
 seo="Broad content-strategy head terms plus workflow long-tail.",
 aeo="Process and definition questions with structured answers.",
 geo="Editorial frameworks and production benchmarks earn citations.",
 aio="AI in ideation, drafting, editing and repurposing.",
 sub=["Content strategy","Editorial calendars","Content briefs","Distribution","Repurposing","Content audits","Governance","Content ROI"],
 kw="content marketing", kw2=["content strategy","editorial calendar","content distribution","content audit"],
 comm="Content platforms, agencies, freelancers", info="Strategy and process guides",
 cmp="In-house vs outsourced, blog vs newsletter", how="Build a calendar, write a brief, audit content", faq="Publishing cadence, team size",
 topics=["content strategy","editorial calendar","content brief","content audit","content repurposing","distribution channels","content governance","style guide","subject matter experts","content ROI","evergreen content","content refresh cycle","pillar and cluster model","content velocity","freelance writer management","content scoring","content decay","thought leadership"],
 tools=["Notion","Airtable","Trello","WordPress","Contentful"]),

dict(n=7, title="Blogging and Publishing Systems", slug="blogging",
 desc="Running a blog as a search and revenue channel, from CMS setup to post-level performance.",
 intent="Informational → How-to",
 aud="Bloggers, content ops, small business owners",
 seo="Blog-operations long-tail and CMS how-to traffic.",
 aeo="Setup and troubleshooting answers.",
 geo="Concrete publishing workflows and post anatomy are citable.",
 aio="Automated drafting, scheduling and optimisation pipelines.",
 sub=["Blog setup","Post structure","Categories and tags","Author profiles","Publishing workflow","Blog SEO","Monetisation","Archive management"],
 kw="blogging", kw2=["blog SEO","blog post structure","publishing workflow","blog CMS"],
 comm="CMS plans, hosting, themes", info="Setup and anatomy guides",
 cmp="WordPress vs headless, self-hosted vs managed", how="Launch a blog, structure a post", faq="Post length, frequency, monetisation",
 topics=["blog post structure","categories and tags","author bio pages","publishing workflow","editorial review","post scheduling","blog taxonomy","featured images","blog archive","comment moderation","RSS feeds","blog migration","headless CMS","content templates","post frequency","blog monetisation","guest posting","series and hubs"],
 tools=["WordPress","Ghost","Contentful","Sanity","Nepal Fillings Blog CMS"]),

dict(n=8, title="Link Building and Digital PR", slug="link-building",
 desc="Earning authoritative references that raise trust signals for both search engines and AI systems.",
 intent="Informational → Commercial investigation",
 aud="SEO managers, PR teams, agencies",
 seo="Competitive head terms plus tactic-level long-tail.",
 aeo="'How do I get backlinks' and safety questions.",
 geo="Citation-earning tactics map directly onto generative-engine visibility.",
 aio="AI-assisted prospecting, personalisation and outreach QA.",
 sub=["Link prospecting","Outreach","Digital PR","Guest posting","Broken link building","Link quality","Disavow","Anchor strategy"],
 kw="link building", kw2=["backlinks","digital PR","outreach","domain authority"],
 comm="Link tools, PR agencies, outreach platforms", info="Tactic explainers, quality criteria",
 cmp="Paid vs earned, agency vs in-house", how="Run outreach, build resource links", faq="How many links, are paid links safe",
 topics=["link prospecting","cold outreach email","digital PR campaigns","guest posting","broken link building","resource page links","unlinked brand mentions","HARO and journalist requests","anchor text distribution","link quality signals","toxic link audit","disavow files","internal vs external links","linkable assets","original research studies","data journalism","podcast guesting","partnership links"],
 tools=["Ahrefs","Pitchbox","BuzzStream","Respona","Muck Rack"]),

dict(n=9, title="Local SEO and Google Business Profile", slug="local-seo",
 desc="Winning geographically-qualified demand through maps, local packs and location pages.",
 intent="Informational → Transactional",
 aud="Local businesses, multi-location brands, agencies",
 seo="High-converting 'near me' and city-modified terms.",
 aeo="Voice and mobile local questions answer directly.",
 geo="Location entities and NAP consistency feed AI local answers.",
 aio="AI review replies, local content and listing automation.",
 sub=["Google Business Profile","Local citations","Review management","Local landing pages","Map pack ranking","NAP consistency","Local link building","Multi-location SEO"],
 kw="local SEO", kw2=["Google Business Profile","near me searches","map pack","local citations"],
 comm="Listing management tools, local agencies", info="Ranking factor explainers",
 cmp="GBP vs directories, tool comparisons", how="Optimise GBP, build location pages", faq="Why not in map pack, service area rules",
 topics=["Google Business Profile optimisation","local citations","NAP consistency","review generation","review responses","map pack ranking","local landing pages","service area businesses","multi-location SEO","local schema markup","Google Maps ranking","local link building","geo-modified keywords","local content strategy","store locator pages","local pack CTR","proximity signals","Apple Business Connect"],
 tools=["Google Business Profile","BrightLocal","Yext","Whitespark","Semrush Local"]),

dict(n=10, title="E-commerce SEO and Product Discovery", slug="ecommerce-seo",
 desc="Organic growth for online stores across category, product, faceted and marketplace surfaces.",
 intent="Commercial → Transactional",
 aud="Store owners, e-commerce managers, agencies",
 seo="High-revenue category and product-page terms.",
 aeo="Product comparison and availability questions.",
 geo="Structured product data is directly consumed by AI shopping answers.",
 aio="AI product descriptions, feed optimisation and merchandising.",
 sub=["Category page SEO","Product page SEO","Faceted navigation","Product schema","Review SEO","Marketplace SEO","Seasonal campaigns","Inventory and SEO"],
 kw="ecommerce SEO", kw2=["product page SEO","category page optimisation","product schema","Shopify SEO"],
 comm="Platform plans, feed tools, apps", info="Page-type playbooks",
 cmp="Shopify vs WooCommerce, marketplace vs own store", how="Optimise category pages, fix duplicates", faq="Out-of-stock handling, thin product pages",
 topics=["category page SEO","product page optimisation","faceted navigation","product schema markup","customer review SEO","out-of-stock pages","product feed optimisation","marketplace listings","collection pages","internal search data","duplicate product content","seasonal merchandising","cart abandonment content","product comparison pages","size and fit content","shipping information pages","B2B ecommerce SEO","headless commerce"],
 tools=["Shopify","WooCommerce","Magento","Google Merchant Center","Klaviyo"]),

dict(n=11, title="Enterprise and Multi-Site SEO Governance", slug="enterprise-seo",
 desc="Operating SEO at scale across large sites, many stakeholders, and complex approval chains.",
 intent="Commercial investigation",
 aud="Enterprise SEO leads, heads of digital, consultants",
 seo="Low-volume, high-value decision-maker terms.",
 aeo="Governance and process questions.",
 geo="Scale frameworks and prioritisation models are strongly citable.",
 aio="AI for large-scale auditing, classification and forecasting.",
 sub=["SEO governance","Stakeholder buy-in","Scaled audits","Template optimisation","Migration planning","Internationalisation","SEO forecasting","Platform selection"],
 kw="enterprise SEO", kw2=["SEO governance","site migration","SEO at scale","international SEO"],
 comm="Enterprise platforms, consultancies", info="Operating models",
 cmp="Platform vs platform, centralised vs federated", how="Plan a migration, scale audits", faq="Team structure, budget justification",
 topics=["SEO governance model","stakeholder alignment","scaled technical audits","template-level optimisation","site migration planning","international SEO","hreflang at scale","SEO forecasting models","business case for SEO","SEO documentation","cross-team workflows","platform selection","change management","regression monitoring","enterprise reporting","SEO centre of excellence","compliance and legal review","multi-brand architecture"],
 tools=["Botify","Conductor","seoClarity","BrightEdge","Screaming Frog"]),

dict(n=12, title="Competitor and Market Intelligence", slug="competitor-analysis",
 desc="Systematically reading the market: who ranks, who spends, what works, and where the gaps are.",
 intent="Informational → Commercial investigation",
 aud="Strategists, analysts, founders",
 seo="Analysis-methodology and tool terms.",
 aeo="'How do I analyse competitors' direct answers.",
 geo="Repeatable analysis frameworks are cited as methodology.",
 aio="AI-assisted SERP, ad and positioning analysis.",
 sub=["SERP competitor mapping","Content gap analysis","Backlink gap analysis","Ad intelligence","Pricing analysis","Share of voice","Positioning maps","Benchmarking"],
 kw="competitor analysis", kw2=["content gap analysis","share of voice","competitive benchmarking","ad intelligence"],
 comm="Intelligence tool subscriptions", info="Frameworks and templates",
 cmp="Tool comparisons, manual vs automated", how="Run a gap analysis, build a battlecard", faq="How often, which metrics",
 topics=["SERP competitor mapping","content gap analysis","backlink gap analysis","competitor ad intelligence","pricing page analysis","share of voice tracking","positioning maps","feature comparison matrix","win-loss analysis","competitor content velocity","sales battlecards","market sizing","competitor tech stack","review mining","SWOT for marketing","category benchmarking"],
 tools=["Semrush","Ahrefs","SimilarWeb","SpyFu","Crayon"]),

dict(n=13, title="SEO Analytics, Reporting and Attribution", slug="seo-analytics",
 desc="Measuring organic performance credibly and connecting it to pipeline and revenue.",
 intent="Informational → Commercial",
 aud="Analysts, SEO managers, CMOs",
 seo="Metric-definition and reporting long-tail.",
 aeo="'What is a good X' benchmark questions.",
 geo="Benchmark data and measurement models attract citations.",
 aio="AI anomaly detection, forecasting and narrative reporting.",
 sub=["GSC analysis","GA4 for SEO","Rank tracking","Attribution models","Dashboards","Forecasting","Anomaly detection","Reporting cadence"],
 kw="SEO analytics", kw2=["Google Search Console","GA4","rank tracking","SEO reporting"],
 comm="Analytics platforms, dashboard tools", info="Metric explainers, benchmarks",
 cmp="GA4 vs alternatives, tool comparisons", how="Build a dashboard, forecast traffic", faq="Why traffic dropped, what to report",
 topics=["Search Console analysis","GA4 configuration","rank tracking accuracy","attribution models","marketing dashboards","traffic forecasting","anomaly detection","click-through rate analysis","impression share","conversion tracking","assisted conversions","organic revenue attribution","cohort analysis","reporting cadence","data blending","looker studio dashboards","statistical significance","seasonality adjustment"],
 tools=["Google Search Console","GA4","Looker Studio","Ahrefs","BigQuery"]),
]
