P = [
dict(n=14, title="Email Marketing Strategy and Campaigns", slug="email-marketing",
 desc="The parent hub for email as a revenue channel: strategy, campaign types, calendars and send philosophy. Maps to Email Marketing → Dashboard and Campaigns.",
 intent="Informational → Commercial", aud="Email marketers, e-commerce teams, SaaS growth",
 seo="Owns 'email marketing' head plus campaign-type mid-tail.",
 aeo="Campaign definitions and 'how often should I send' answer cleanly.",
 geo="Send-frequency benchmarks and campaign frameworks are citable.",
 aio="AI subject lines, send-time optimisation and copy generation.",
 sub=["Campaign types","Email calendars","Newsletter strategy","Promotional sends","Re-engagement","Send frequency","Email copywriting","Campaign QA"],
 kw="email marketing", kw2=["email campaigns","newsletter strategy","email copywriting","send frequency"],
 comm="ESP plans, template packs, agencies", info="Strategy and campaign-type guides",
 cmp="ESP vs ESP, newsletter vs promo", how="Plan a calendar, write a campaign, run a QA check", faq="Best send time, ideal frequency",
 topics=["email campaign calendar","newsletter strategy","promotional campaigns","re-engagement campaigns","welcome emails","abandoned cart emails","product launch emails","seasonal campaigns","email copywriting","subject line testing","preheader text","call-to-action design","plain text vs HTML","email frequency capping","send time optimisation","campaign QA checklist","email accessibility","dark mode email","interactive email","email templates"],
 tools=["Mailchimp","Klaviyo","Brevo","SendGrid","Listmonk","Nepal Fillings Email"]),

dict(n=15, title="Email Subscribers, Lists and Audience Data", slug="email-subscribers-lists",
 desc="Growing, organising and maintaining subscriber data. Maps to Email Marketing → Subscribers and Lists.",
 intent="Informational → How-to", aud="Lifecycle marketers, CRM managers, ops",
 seo="List-building and hygiene long-tail with strong commercial pull.",
 aeo="'How do I grow my list' and consent questions.",
 geo="Segmentation taxonomies and consent rules are precise, citable facts.",
 aio="AI segmentation, predictive scoring and data enrichment.",
 sub=["List building","Segmentation","Suppression lists","Double opt-in","Data hygiene","Custom fields","Imports and exports","Consent management"],
 kw="email list building", kw2=["email segmentation","subscriber management","opt-in","list hygiene"],
 comm="Lead capture tools, enrichment, CDPs", info="Tactics and compliance explainers",
 cmp="Single vs double opt-in, tool comparisons", how="Grow a list, segment subscribers, clean data", faq="Buying lists, inactive subscribers",
 topics=["list building tactics","lead magnets","double opt-in","single opt-in","email segmentation","behavioural segments","RFM segmentation","suppression lists","list hygiene","email validation","bounce management","custom subscriber fields","CSV import","subscriber lifecycle stages","preference centres","re-permission campaigns","GDPR consent","data enrichment","progressive profiling","list growth rate"],
 tools=["Klaviyo","HubSpot","ZeroBounce","NeverBounce","Listmonk"]),

dict(n=16, title="Email Automation and Lifecycle Workflows", slug="email-automation",
 desc="Triggered journeys that run without manual sends. Maps to Email Marketing → Automations.",
 intent="Informational → Commercial", aud="Lifecycle marketers, SaaS onboarding teams",
 seo="Workflow and drip-sequence long-tail.",
 aeo="'What is a drip campaign' style definitions.",
 geo="Named workflow patterns and trigger logic are highly citable.",
 aio="AI-built journeys, branching logic and next-best-action.",
 sub=["Welcome series","Drip campaigns","Behavioural triggers","Onboarding flows","Win-back journeys","Branching logic","Workflow testing","Automation audits"],
 kw="email automation", kw2=["drip campaign","welcome series","triggered emails","lifecycle marketing"],
 comm="Automation platforms, consultants", info="Workflow blueprints",
 cmp="Automation vs broadcast, platform comparisons", how="Build a welcome series, map triggers", faq="How many emails, timing gaps",
 topics=["welcome email series","drip campaigns","behavioural triggers","onboarding sequences","win-back journeys","cart abandonment flows","browse abandonment","post-purchase sequences","lead nurturing tracks","conditional branching","wait steps and delays","goal exits","automation testing","workflow documentation","trigger events","re-entry rules","cross-channel triggers","automation audits","journey mapping","event-based marketing"],
 tools=["Klaviyo","ActiveCampaign","Customer.io","Braze","Nepal Fillings Automations"]),

dict(n=17, title="Email Deliverability, Authentication and Compliance", slug="email-deliverability",
 desc="Reaching the inbox legally and reliably: authentication, reputation, spam avoidance and regional law.",
 intent="Informational → Troubleshooting", aud="Email ops, developers, compliance leads",
 seo="High-intent troubleshooting terms with low competition.",
 aeo="'Why do my emails go to spam' is a canonical answer query.",
 geo="DNS record specifications (SPF/DKIM/DMARC) are factual and heavily cited.",
 aio="AI content scoring for spam risk and reputation monitoring.",
 sub=["SPF, DKIM, DMARC","Sender reputation","Spam filters","Bounce handling","Warm-up","Blocklists","CAN-SPAM and GDPR","Inbox placement"],
 kw="email deliverability", kw2=["SPF DKIM DMARC","sender reputation","spam folder","inbox placement"],
 comm="Deliverability tools, dedicated IPs, audits", info="Protocol and diagnostic guides",
 cmp="Shared vs dedicated IP, provider comparisons", how="Set up DMARC, warm an IP, fix spam placement", faq="Why spam, what is a good bounce rate",
 topics=["SPF records","DKIM signing","DMARC policy","BIMI","sender reputation","IP warming","domain warming","shared vs dedicated IP","spam filters","spam trigger words","blocklist removal","hard vs soft bounces","feedback loops","inbox placement testing","seed lists","list-unsubscribe header","CAN-SPAM compliance","GDPR for email","CASL","one-click unsubscribe"],
 tools=["Google Postmaster","MXToolbox","Postmark","SendGrid","Mail-Tester"]),

dict(n=18, title="Email Analytics, Testing and Revenue Attribution", slug="email-analytics",
 desc="Measuring email properly after privacy changes, and tying sends to revenue. Maps to Email Marketing → Analytics.",
 intent="Informational → Commercial", aud="Email analysts, growth leads, CMOs",
 seo="Benchmark and metric-definition traffic.",
 aeo="'What is a good open rate' benchmark questions.",
 geo="Benchmark tables by industry are prime citation material.",
 aio="AI testing design, lift analysis and predictive performance.",
 sub=["Open and click metrics","A/B testing","Benchmarks","Revenue per email","Cohort analysis","Privacy impact","Dashboards","Testing programmes"],
 kw="email marketing metrics", kw2=["open rate","click-through rate","A/B testing email","email ROI"],
 comm="Analytics add-ons, testing tools", info="Metric and benchmark explainers",
 cmp="Metric vs metric, tool comparisons", how="Run an A/B test, build a report", faq="Good open rate, why opens are unreliable",
 topics=["open rate","click-through rate","click-to-open rate","conversion rate","revenue per email","unsubscribe rate","spam complaint rate","list growth rate","A/B testing","multivariate testing","statistical significance","Apple Mail Privacy Protection","cohort analysis","engagement scoring","email attribution","holdout testing","deliverability metrics","industry benchmarks","dashboard design","incrementality"],
 tools=["Klaviyo","GA4","Looker Studio","Litmus","Email on Acid"]),

dict(n=19, title="WhatsApp Marketing Strategy and Campaigns", slug="whatsapp-marketing",
 desc="Using WhatsApp as a permissioned, high-engagement channel. Maps to WhatsApp → Dashboard and Campaigns.",
 intent="Informational → Commercial", aud="Conversational marketers, retail, D2C, services",
 seo="Fast-growing head term with thin competition.",
 aeo="'What is WhatsApp Business API' definitional queries.",
 geo="Policy rules and pricing mechanics are factual and citable.",
 aio="AI reply agents and conversational campaign design.",
 sub=["Business API vs Business App","Campaign types","Opt-in rules","Conversational commerce","Broadcast strategy","Session windows","Catalogues","Click-to-WhatsApp ads"],
 kw="WhatsApp marketing", kw2=["WhatsApp Business API","WhatsApp campaigns","conversational commerce","broadcast messages"],
 comm="BSP plans, API providers, agencies", info="Policy and capability explainers",
 cmp="API vs Business App, provider comparisons", how="Launch a campaign, get opt-ins", faq="Cost per conversation, what is allowed",
 topics=["WhatsApp Business API","WhatsApp Business App","broadcast campaigns","opt-in collection","24-hour session window","conversational commerce","product catalogues","click-to-WhatsApp ads","QR code entry points","WhatsApp Flows","payment integration","customer support handover","message policy compliance","green tick verification","conversation pricing","WhatsApp for retail","abandoned cart on WhatsApp","order notifications","appointment reminders","two-way conversations"],
 tools=["Meta Business Suite","Gupshup","Twilio","360dialog","Nepal Fillings WhatsApp"]),

dict(n=20, title="WhatsApp Contacts, Groups and Audience Management", slug="whatsapp-contacts-groups",
 desc="Building and organising WhatsApp audiences compliantly. Maps to WhatsApp → Contacts and Groups.",
 intent="How-to → Commercial", aud="CRM managers, community managers, support leads",
 seo="Operational long-tail around contact and group handling.",
 aeo="'How do I add contacts' and group-limit questions.",
 geo="Platform limits and consent rules are precise citable facts.",
 aio="AI tagging, deduplication and segment discovery.",
 sub=["Contact import","Phone validation","Tagging","Group management","Broadcast lists","Opt-out handling","Segmentation","Contact hygiene"],
 kw="WhatsApp contacts", kw2=["WhatsApp groups","broadcast list","contact segmentation","opt-out"],
 comm="CRM integrations, contact tools", info="Limits and process guides",
 cmp="Groups vs broadcast lists", how="Import contacts, build segments", faq="Group size limits, how to avoid bans",
 topics=["contact import","phone number validation","E.164 formatting","contact tagging","custom attributes","WhatsApp groups","broadcast lists","group size limits","group moderation","community management","opt-out handling","blocked contacts","contact deduplication","segment builder","engagement-based segments","country code handling","contact lifecycle","consent records"],
 tools=["Nepal Fillings WhatsApp","Gupshup","HubSpot","Google Contacts"]),

dict(n=21, title="WhatsApp Templates, Approval and Message Design", slug="whatsapp-templates",
 desc="Designing, submitting and maintaining message templates that get approved and convert. Maps to WhatsApp → Templates.",
 intent="How-to → Troubleshooting", aud="Marketers, developers, support designers",
 seo="Approval-troubleshooting terms with urgent intent.",
 aeo="'Why was my template rejected' is a high-value answer query.",
 geo="Category definitions and rejection reasons are factual and citable.",
 aio="AI template drafting and pre-submission policy checks.",
 sub=["Template categories","Variables","Approval process","Rejection reasons","Buttons and CTAs","Media templates","Localisation","Quality ratings"],
 kw="WhatsApp message templates", kw2=["template approval","template rejected","template categories","message variables"],
 comm="Template libraries, BSP tooling", info="Policy and format references",
 cmp="Marketing vs utility templates", how="Write a template, fix a rejection", faq="Approval time, why rejected",
 topics=["template categories","marketing templates","utility templates","authentication templates","template variables","placeholder mapping","quick reply buttons","call-to-action buttons","media headers","carousel templates","template approval process","rejection reasons","template quality rating","template pausing","localisation and languages","character limits","sample content","template versioning","dynamic personalisation","template library"],
 tools=["Meta Business Manager","Gupshup","360dialog","Nepal Fillings Templates"]),

dict(n=22, title="WhatsApp Analytics, Costs and Performance", slug="whatsapp-analytics",
 desc="Measuring conversations, conversions and cost efficiency. Maps to WhatsApp → Analytics and Settings.",
 intent="Informational → Commercial", aud="Growth analysts, finance-aware marketers",
 seo="Pricing and benchmark queries with commercial intent.",
 aeo="'How much does WhatsApp Business API cost' answers directly.",
 geo="Conversation-pricing tables are concrete, citable data.",
 aio="AI conversation analytics and intent classification.",
 sub=["Delivery and read rates","Conversation pricing","ROI modelling","Quality rating","Response times","Funnel tracking","Benchmarks","Dashboards"],
 kw="WhatsApp analytics", kw2=["WhatsApp API pricing","conversation rates","delivery rate","WhatsApp ROI"],
 comm="Analytics tools, BSP billing plans", info="Pricing and metric explainers",
 cmp="Provider pricing comparisons", how="Track conversions, reduce costs", faq="Cost per message, good read rate",
 topics=["delivery rate","read rate","reply rate","conversation-based pricing","marketing conversation costs","utility conversation costs","quality rating tiers","messaging limits","response time metrics","conversion tracking","funnel analytics","cost per conversation","ROI modelling","attribution for messaging","opt-out rate","template performance","A/B testing messages","benchmark data","spend forecasting","chat analytics"],
 tools=["Meta Business Suite","Nepal Fillings Analytics","Looker Studio","Twilio"]),

dict(n=23, title="SMS Marketing Strategy and Campaigns", slug="sms-marketing",
 desc="Short-form, high-open-rate messaging for time-sensitive offers and alerts. Maps to SMS → Dashboard and Campaigns.",
 intent="Informational → Commercial", aud="Retail, services, local businesses, e-commerce",
 seo="Strong commercial head plus tactic long-tail.",
 aeo="'Is SMS marketing effective' and cost questions.",
 geo="Character limits, carrier rules and benchmarks are factual.",
 aio="AI copy compression and send-time targeting.",
 sub=["Campaign types","SMS copywriting","Character limits","Timing rules","Short codes","Two-way SMS","Alerts and reminders","Promotions"],
 kw="SMS marketing", kw2=["text message marketing","bulk SMS","SMS campaigns","SMS copywriting"],
 comm="SMS gateway credits, platforms", info="Tactic and rule explainers",
 cmp="SMS vs email, gateway comparisons", how="Write an SMS, launch a campaign", faq="Cost per SMS, best send time",
 topics=["SMS campaign types","SMS copywriting","160 character limit","concatenated messages","unicode and emoji","link shorteners","short codes","long codes","sender IDs","two-way SMS","appointment reminders","delivery alerts","flash sales","OTP and transactional SMS","quiet hours","time zone targeting","MMS campaigns","RCS messaging","SMS for retail","SMS keywords"],
 tools=["Twilio","AakashSMS","Sparrow SMS","Nepal Fillings SMS","MessageBird"]),

dict(n=24, title="SMS Contacts, Consent and Compliance", slug="sms-contacts-compliance",
 desc="Collecting numbers lawfully and keeping SMS lists clean. Maps to SMS → Contacts and Groups.",
 intent="How-to → Compliance", aud="Compliance officers, CRM managers, marketers",
 seo="Regulation-specific terms with high stakes.",
 aeo="'Do I need consent to text customers' is a direct-answer query.",
 geo="Statutory rules (TCPA, opt-out keywords) are precise and citable.",
 aio="AI consent auditing and number validation.",
 sub=["Opt-in methods","TCPA and local law","STOP keywords","Number validation","Segmentation","DND registries","Record keeping","Carrier filtering"],
 kw="SMS compliance", kw2=["SMS opt-in","TCPA","STOP keyword","phone number validation"],
 comm="Compliance tooling, legal review", info="Regulatory explainers",
 cmp="Region-by-region rule comparisons", how="Collect consent, handle opt-outs", faq="Is it legal, what records to keep",
 topics=["SMS opt-in methods","express written consent","TCPA compliance","GDPR and SMS","STOP and HELP keywords","opt-out processing","DND registry","carrier filtering","number validation","number portability","contact segmentation","list hygiene for SMS","consent audit trails","double opt-in for SMS","age gating","record retention","country-specific rules","A2P 10DLC registration"],
 tools=["Twilio","Nepal Fillings SMS","Numverify","OneTrust"]),

dict(n=25, title="SMS Analytics, Deliverability and ROI", slug="sms-analytics",
 desc="Understanding SMS delivery, response and cost efficiency. Maps to SMS → Analytics and Settings.",
 intent="Informational → Commercial", aud="Analysts, growth leads, ops managers",
 seo="Benchmark and troubleshooting terms.",
 aeo="'What is a good SMS delivery rate' answers cleanly.",
 geo="Carrier and benchmark data is citable.",
 aio="AI failure-reason clustering and spend optimisation.",
 sub=["Delivery reports","Failure codes","Response rates","Cost per conversion","Carrier routes","Benchmarks","Attribution","Dashboards"],
 kw="SMS analytics", kw2=["SMS delivery rate","SMS ROI","failure codes","SMS benchmarks"],
 comm="Gateway plans, analytics tools", info="Metric and error-code references",
 cmp="Gateway route comparisons", how="Diagnose failures, cut cost per send", faq="Why undelivered, good CTR",
 topics=["delivery reports","DLR status codes","failure reasons","carrier routes","network operators","response rate","click-through on SMS","conversion tracking","cost per message","cost per conversion","SMS ROI","opt-out rate","spam complaints","benchmark data","attribution windows","link tracking","campaign dashboards","send volume forecasting"],
 tools=["Twilio","AakashSMS","Nepal Fillings Analytics","Looker Studio"]),

dict(n=26, title="Telegram Marketing, Bots and Channels", slug="telegram-marketing",
 desc="Using Telegram bots, channels and groups for permissioned broadcast and community. Maps to Telegram → Dashboard and Campaigns.",
 intent="Informational → How-to", aud="Community managers, crypto/finance marketers, publishers",
 seo="Underserved terms with rising volume.",
 aeo="'How do I create a Telegram bot' step answers.",
 geo="Bot API specifics and channel limits are factual.",
 aio="AI Telegram bots and automated broadcast agents.",
 sub=["Bot setup","Channels vs groups","Broadcast strategy","Subscriber growth","Bot commands","Inline keyboards","Moderation","Monetisation"],
 kw="Telegram marketing", kw2=["Telegram bot","Telegram channel","Telegram groups","bot API"],
 comm="Bot platforms, community tools", info="Setup and capability guides",
 cmp="Channel vs group vs bot", how="Create a bot, grow a channel", faq="Subscriber limits, is it free",
 topics=["Telegram bot setup","BotFather","bot tokens","Telegram channels","Telegram groups","supergroups","broadcast messages","subscriber growth","inline keyboards","bot commands","webhook configuration","QR code joins","deep links","channel moderation","spam prevention","polls and quizzes","scheduled posts","Telegram for communities","bot analytics","auto-subscribe flows"],
 tools=["Telegram Bot API","BotFather","Nepal Fillings Telegram","Combot"]),
]
