P = [
dict(n=27, title="Telegram Contacts, Groups and Community Growth", slug="telegram-contacts-groups",
 desc="Growing and governing Telegram audiences. Maps to Telegram → Contacts and Groups.",
 intent="How-to", aud="Community managers, moderators, growth teams",
 seo="Community-operations long-tail.",
 aeo="Growth and moderation how-to answers.",
 geo="Moderation frameworks and limits are citable.",
 aio="AI moderation and member scoring.",
 sub=["Subscriber acquisition","Group vs channel","Moderation","Anti-spam","Segmentation","Engagement tactics","Admin roles","Retention"],
 kw="Telegram community", kw2=["Telegram subscribers","group moderation","channel growth","anti-spam"],
 comm="Moderation bots, analytics tools", info="Operations guides",
 cmp="Public vs private groups", how="Grow subscribers, moderate at scale", faq="Member limits, how to stop spam",
 topics=["subscriber acquisition","channel growth tactics","public vs private channels","admin roles and permissions","moderation workflows","anti-spam bots","captcha verification","member segmentation","engagement tactics","pinned messages","welcome messages","inactive member cleanup","invite links","referral tracking","community guidelines","topic threads","member retention","cross-promotion"],
 tools=["Combot","Nepal Fillings Telegram","Telegram Analytics","Shieldy"]),

dict(n=28, title="Telegram Analytics and Campaign Performance", slug="telegram-analytics",
 desc="Measuring reach, engagement and conversion on Telegram. Maps to Telegram → Analytics and Settings.",
 intent="Informational", aud="Analysts, community leads",
 seo="Metric-definition and benchmark long-tail.",
 aeo="'What is a good Telegram view rate' answers.",
 geo="Benchmark and view-count mechanics are citable.",
 aio="AI engagement forecasting and content scoring.",
 sub=["View counts","Forward rates","Subscriber churn","Link tracking","Campaign reporting","Benchmarks","Attribution","Bot analytics"],
 kw="Telegram analytics", kw2=["view rate","subscriber growth","forward rate","Telegram ROI"],
 comm="Analytics platforms", info="Metric explainers",
 cmp="Tool comparisons", how="Track conversions, report performance", faq="Good view rate, why views drop",
 topics=["view counts","view rate","forward rate","subscriber growth rate","churn rate","link click tracking","UTM tagging","bot interaction analytics","command usage","campaign reporting","post reach","engagement rate","best posting times","content performance","conversion attribution","benchmark data","cohort retention","spend efficiency"],
 tools=["Telegram Analytics","Combot","Looker Studio","Nepal Fillings Analytics"]),

dict(n=29, title="Facebook Messenger Marketing and Automation", slug="messenger-marketing",
 desc="Conversational marketing on Messenger within Meta policy. Maps to Messenger → Dashboard and Campaigns.",
 intent="Informational → Commercial", aud="D2C brands, support teams, agencies",
 seo="Recovering head term plus policy long-tail.",
 aeo="'What is the 24-hour rule' definitional answers.",
 geo="Policy windows and tag definitions are precise facts.",
 aio="AI chat agents and intent routing.",
 sub=["24-hour window","Message tags","Recurring notifications","Click-to-Messenger ads","Chatbots","Handover protocol","Persistent menu","Welcome flows"],
 kw="Messenger marketing", kw2=["Facebook Messenger bot","24-hour rule","message tags","click-to-Messenger"],
 comm="Chatbot platforms, agencies", info="Policy and capability guides",
 cmp="Messenger vs WhatsApp, platform comparisons", how="Build a bot, set up recurring notifications", faq="What is allowed, cost",
 topics=["24-hour messaging window","message tags","recurring notifications","opt-in for notifications","click-to-Messenger ads","chatbot flows","persistent menu","greeting and welcome screens","quick replies","handover protocol","live agent escalation","ice breakers","sponsored messages","Messenger for support","lead qualification bots","abandoned cart recovery","order updates","conversation routing","NLP intents","Messenger commerce"],
 tools=["Meta Business Suite","ManyChat","Chatfuel","Nepal Fillings Messenger"]),

dict(n=30, title="Messenger Contacts, Segments and Subscriber Growth", slug="messenger-contacts-groups",
 desc="Acquiring and organising Messenger subscribers compliantly. Maps to Messenger → Contacts and Groups.",
 intent="How-to", aud="Growth marketers, community managers",
 seo="Acquisition and segmentation long-tail.",
 aeo="'How do I get Messenger subscribers' answers.",
 geo="Entry-point taxonomy is citable.",
 aio="AI segment discovery and lookalike modelling.",
 sub=["Entry points","Ref links","Checkbox plugin","Segmentation","Tags and attributes","Opt-out handling","List hygiene","Re-engagement"],
 kw="Messenger subscribers", kw2=["Messenger entry points","m.me links","segmentation","opt-in"],
 comm="Bot platform plans", info="Entry-point references",
 cmp="Entry point comparisons", how="Grow subscribers, segment audiences", faq="How to opt in, can I import contacts",
 topics=["m.me links","ref parameters","checkbox plugin","chat plugin on website","QR codes","comment-to-Messenger growth","scan-to-message","subscriber tagging","custom attributes","audience segmentation","engagement-based segments","opt-out handling","subscriber cleanup","re-engagement campaigns","list growth rate","entry point attribution","lead capture in chat","consent tracking"],
 tools=["ManyChat","Meta Business Suite","Nepal Fillings Messenger"]),

dict(n=31, title="Messenger Analytics and Conversational ROI", slug="messenger-analytics",
 desc="Measuring conversational performance and revenue. Maps to Messenger → Analytics and Settings.",
 intent="Informational → Commercial", aud="Analysts, growth leads",
 seo="Benchmark and measurement long-tail.",
 aeo="Benchmark questions with direct answers.",
 geo="Conversational benchmarks are citable data.",
 aio="AI conversation scoring and deflection measurement.",
 sub=["Open and click rates","Flow drop-off","Bot containment","Response time","Revenue attribution","Benchmarks","Dashboards","Testing"],
 kw="Messenger analytics", kw2=["chatbot metrics","conversation rate","bot containment","Messenger ROI"],
 comm="Analytics tooling", info="Metric explainers",
 cmp="Channel performance comparisons", how="Measure a bot, cut drop-off", faq="Good open rate, how to measure ROI",
 topics=["message open rate","click-through rate","flow completion rate","drop-off analysis","bot containment rate","escalation rate","first response time","resolution time","conversation volume","revenue per conversation","attribution modelling","A/B testing flows","funnel visualisation","cohort analysis","CSAT in chat","deflection savings","benchmark data","dashboard design"],
 tools=["ManyChat","Meta Business Suite","Looker Studio","Nepal Fillings Analytics"]),

dict(n=32, title="Blog CMS Operations: Posts, Categories and Tags", slug="blog-cms-operations",
 desc="Running the content management layer: post lifecycle, taxonomy and publishing hygiene. Maps to Blog CMS → Posts, Categories, Tags.",
 intent="How-to", aud="Content ops, editors, site managers",
 seo="CMS-operations long-tail.",
 aeo="Taxonomy and workflow questions.",
 geo="Taxonomy design rules are citable frameworks.",
 aio="AI tagging, categorisation and metadata generation.",
 sub=["Post lifecycle","Category architecture","Tag governance","Drafts and scheduling","Revisions","Bulk editing","Media library","Permalinks"],
 kw="blog CMS", kw2=["content taxonomy","categories and tags","post workflow","permalinks"],
 comm="CMS plans, plugins", info="Operations and taxonomy guides",
 cmp="Categories vs tags, CMS comparisons", how="Design a taxonomy, set up workflow", faq="How many categories, tags vs categories",
 topics=["post lifecycle states","draft and review workflow","scheduled publishing","category architecture","tag governance","taxonomy depth","permalink structure","slug conventions","post revisions","bulk editing","media library management","featured image standards","content templates","duplicate content control","noindex rules for tags","archive pagination","related posts logic","content migration","CMS roles and permissions","editorial approvals"],
 tools=["WordPress","Ghost","Nepal Fillings Blog CMS","Contentful"]),

dict(n=33, title="Author Authority, E-E-A-T and Content Credibility", slug="author-authority-eeat",
 desc="Building demonstrable expertise signals for search and AI systems. Maps to Blog CMS → Authors.",
 intent="Informational", aud="Editors, SEO leads, subject experts",
 seo="E-E-A-T and author-signal terms.",
 aeo="'What is E-E-A-T' definitional answers.",
 geo="Author entity signals directly influence AI citation choices.",
 aio="AI disclosure, provenance and human review policies.",
 sub=["Author bio pages","Author schema","Credential signals","Original research","Editorial policy","Fact-checking","AI disclosure","Expert review"],
 kw="E-E-A-T", kw2=["author authority","author schema","editorial policy","content credibility"],
 comm="Expert networks, review services", info="Signal and policy explainers",
 cmp="AI vs human content credibility", how="Build author pages, add schema", faq="Does E-E-A-T affect ranking, do I need bylines",
 topics=["E-E-A-T signals","experience signals","author bio pages","author schema markup","credential display","about and contact pages","editorial policy pages","fact-checking process","source citation standards","original research","first-hand experience","expert review workflows","AI content disclosure","content provenance","bylines and attribution","author entity building","knowledge panel for authors","trust signals","corrections policy","transparency pages"],
 tools=["Schema.org","Google Search Console","WordPress","Nepal Fillings Authors"]),

dict(n=34, title="Blog Analytics, Content ROI and Optimization Cycles", slug="blog-analytics",
 desc="Measuring blog performance and running refresh cycles. Maps to Blog CMS → Analytics and Settings.",
 intent="Informational → Commercial", aud="Content leads, analysts, CMOs",
 seo="Content-measurement long-tail.",
 aeo="'How do I measure content ROI' answers.",
 geo="Refresh methodologies and decay curves are citable.",
 aio="AI content scoring, decay detection and refresh prioritisation.",
 sub=["Traffic analysis","Engagement metrics","Content decay","Refresh prioritisation","Conversion tracking","Content ROI","Dashboards","Pruning"],
 kw="blog analytics", kw2=["content ROI","content decay","content refresh","engagement metrics"],
 comm="Analytics platforms, content tools", info="Measurement frameworks",
 cmp="Metric comparisons, tool comparisons", how="Find decaying posts, prioritise refreshes", faq="Which metrics matter, when to update",
 topics=["blog traffic analysis","scroll depth","time on page","engagement rate","content decay curves","refresh prioritisation","content pruning","conversion tracking","assisted conversions","content ROI models","cost per acquisition from content","top-of-funnel measurement","internal search analysis","exit pages","reader cohorts","subscriber conversion","dashboard design","content scoring models"],
 tools=["GA4","Google Search Console","Looker Studio","Nepal Fillings Analytics"]),

dict(n=35, title="Answer Engine Optimization (AEO)", slug="answer-engine-optimization",
 desc="Structuring content so engines and assistants can extract a direct, correct answer.",
 intent="Informational", aud="SEO leads, content strategists",
 seo="Emerging head term with fast-growing demand.",
 aeo="The pillar is itself the discipline — maximal snippet capture.",
 geo="Answer formatting rules are cited by AI systems explaining themselves.",
 aio="Overlaps with assistant-driven discovery.",
 sub=["Featured snippets","People Also Ask","FAQ schema","Answer formatting","Voice search","Question research","Concise answers","Snippet defence"],
 kw="answer engine optimization", kw2=["featured snippets","People Also Ask","FAQ schema","voice search"],
 comm="AEO tooling, audits", info="Formatting and structure guides",
 cmp="AEO vs SEO, snippet formats", how="Win a snippet, format an answer", faq="What is AEO, does it replace SEO",
 topics=["featured snippets","paragraph snippets","list snippets","table snippets","People Also Ask","FAQ schema","HowTo schema","question research","answer-first writing","concise answer blocks","definition boxes","voice search optimisation","conversational queries","snippet defence","zero-click search","direct answer formatting","entity disambiguation","semantic markup","Q&A pages","structured answers"],
 tools=["AlsoAsked","AnswerThePublic","Google Search Console","Semrush"]),

dict(n=36, title="Generative Engine Optimization (GEO)", slug="generative-engine-optimization",
 desc="Earning visibility and citation inside AI-generated answers from ChatGPT, Perplexity, Gemini and AI Overviews.",
 intent="Informational → Commercial investigation", aud="Forward-looking SEO leads, founders",
 seo="New head term with low competition and high strategic value.",
 aeo="Definitional questions about GEO.",
 geo="The pillar is the discipline — original frameworks maximise citation odds.",
 aio="Directly adjacent to AI search behaviour.",
 sub=["AI citation mechanics","Brand mentions in LLMs","AI Overviews","Perplexity visibility","Content structuring for LLMs","llms.txt","Measuring AI visibility","Source authority"],
 kw="generative engine optimization", kw2=["AI search visibility","AI Overviews","LLM citations","Perplexity SEO"],
 comm="GEO tracking tools, consulting", info="Mechanism and framework guides",
 cmp="GEO vs SEO vs AEO", how="Get cited by AI, track AI visibility", faq="What is GEO, does it matter yet",
 topics=["AI citation mechanics","Google AI Overviews","Perplexity visibility","ChatGPT search","Gemini answers","brand mentions in LLMs","LLM training data","retrieval augmented generation","llms.txt","AI crawler permissions","content chunking for retrieval","structured facts","original data for citation","source authority signals","measuring AI visibility","AI referral traffic","prompt-level ranking","answer share of voice","entity consistency","citation-worthy formatting"],
 tools=["Perplexity","ChatGPT","Profound","Otterly","Google Search Console"]),

dict(n=37, title="AI Search Optimization and AI-Assisted Marketing (AIO)", slug="ai-optimization",
 desc="Using AI across the marketing stack and optimising for AI-mediated discovery.",
 intent="Informational → Commercial", aud="Marketing operators, growth engineers",
 seo="Fast-rising AI-marketing terms.",
 aeo="Tool and capability questions.",
 geo="Workflow blueprints earn citations.",
 aio="The pillar is the discipline.",
 sub=["AI content workflows","AI agents","Prompt engineering","AI personalisation","AI analytics","Human review","AI governance","Tool selection"],
 kw="AI marketing", kw2=["AI SEO","AI content","marketing AI agents","prompt engineering"],
 comm="AI tool subscriptions, consulting", info="Workflow and capability guides",
 cmp="AI tool comparisons, AI vs human", how="Build an AI workflow, write prompts", faq="Will AI replace marketers, is AI content penalised",
 topics=["AI content workflows","prompt engineering for marketers","marketing AI agents","AI personalisation","AI analytics","predictive segmentation","AI copywriting","AI image generation","AI video generation","human-in-the-loop review","AI governance policy","hallucination controls","AI tool selection","retrieval augmented marketing","AI for keyword research","AI for ad copy","AI chat agents","AI workflow automation","model selection","AI cost management"],
 tools=["Claude","ChatGPT","Gemini","Zapier","Make"]),

dict(n=38, title="Marketing Automation and Workflow Orchestration", slug="marketing-automation",
 desc="Connecting channels, data and triggers into reliable automated systems.",
 intent="Commercial investigation", aud="Marketing ops, RevOps, technical marketers",
 seo="Platform and workflow terms with strong buying intent.",
 aeo="Definition and selection questions.",
 geo="Architecture patterns are citable.",
 aio="AI-driven orchestration and decisioning.",
 sub=["Workflow design","Lead scoring","Cross-channel triggers","Data sync","Integrations","Webhooks","Testing","Platform selection"],
 kw="marketing automation", kw2=["workflow automation","lead scoring","integrations","webhooks"],
 comm="Platform licences, implementation partners", info="Architecture guides",
 cmp="Platform comparisons, build vs buy", how="Build a workflow, sync data", faq="Cost, complexity, where to start",
 topics=["workflow design patterns","lead scoring models","cross-channel orchestration","trigger architecture","data synchronisation","API integrations","webhooks","event tracking","idempotency and retries","error handling","sandbox testing","platform migration","no-code automation","reverse ETL","customer data platforms","consent propagation","automation governance","workflow documentation","SLA monitoring","orchestration at scale"],
 tools=["Zapier","Make","n8n","HubSpot","Customer.io"]),
]
