P = [
dict(n=39, title="Paid Search and Google Ads", slug="google-ads-ppc",
 desc="Buying intent-driven traffic profitably across Google's search and shopping surfaces.",
 intent="Commercial → Transactional", aud="PPC managers, e-commerce, lead-gen businesses",
 seo="High-CPC commercial terms.", aeo="Cost and setup questions answer directly.",
 geo="Auction mechanics and benchmark CPCs are citable facts.", aio="AI bidding, PMax and automated asset generation.",
 sub=["Campaign structure","Keyword match types","Quality Score","Bidding strategies","Performance Max","Shopping ads","Negative keywords","Budget pacing"],
 kw="Google Ads", kw2=["PPC","Quality Score","Performance Max","search ads"],
 comm="Ad spend, management tools, agencies", info="Mechanics and setup guides",
 cmp="Google vs Meta, manual vs automated bidding", how="Structure a campaign, lower CPC", faq="How much should I spend, why is CPC high",
 topics=["campaign structure","ad groups","keyword match types","negative keywords","Quality Score","ad rank","bidding strategies","target ROAS","target CPA","Performance Max","Shopping campaigns","responsive search ads","ad extensions","landing page experience","conversion tracking","budget pacing","dayparting","geo-targeting","audience layering","search terms report"],
 tools=["Google Ads","Google Merchant Center","Optmyzr","Google Analytics 4"]),

dict(n=40, title="Meta Ads and Paid Social", slug="meta-ads-paid-social",
 desc="Paid acquisition across Facebook, Instagram and emerging social ad platforms.",
 intent="Commercial → Transactional", aud="D2C marketers, media buyers, agencies",
 seo="High-volume commercial terms.", aeo="Targeting and cost questions.",
 geo="Algorithm mechanics and benchmark CPMs are citable.", aio="AI creative testing and Advantage+ automation.",
 sub=["Campaign objectives","Audience targeting","Creative testing","Advantage+","Pixel and CAPI","Retargeting","Attribution","Scaling"],
 kw="Meta Ads", kw2=["Facebook ads","Instagram ads","retargeting","Advantage+"],
 comm="Ad spend, creative tools, agencies", info="Platform mechanics",
 cmp="Meta vs TikTok, broad vs narrow targeting", how="Launch a campaign, test creative", faq="Why did costs rise, what budget to start",
 topics=["campaign objectives","audience targeting","lookalike audiences","custom audiences","broad targeting","creative testing frameworks","ad creative formats","UGC ads","video ads","Advantage+ shopping","Meta Pixel","Conversions API","iOS privacy impact","attribution windows","retargeting funnels","budget scaling","creative fatigue","frequency capping","catalogue ads","click-to-message ads"],
 tools=["Meta Ads Manager","Meta Business Suite","Triple Whale","Motion"]),

dict(n=41, title="Social Media Marketing and Community", slug="social-media-marketing",
 desc="Organic social presence, content formats and community building across platforms.",
 intent="Informational → Commercial", aud="Social media managers, brand teams",
 seo="Broad head terms plus platform long-tail.",
 aeo="Best-time-to-post and format questions.", geo="Platform benchmark data is citable.",
 aio="AI scheduling, captioning and trend detection.",
 sub=["Platform strategy","Content formats","Posting cadence","Community management","Social listening","Employee advocacy","Social commerce","Crisis response"],
 kw="social media marketing", kw2=["content calendar","social strategy","community management","social listening"],
 comm="Scheduling tools, agencies", info="Platform and format guides",
 cmp="Platform comparisons, tool comparisons", how="Build a calendar, grow a following", faq="Best time to post, how often",
 topics=["platform selection","content pillars for social","short-form video","carousel posts","posting cadence","social content calendar","community management","social listening","user-generated content","employee advocacy","social commerce","hashtag strategy","engagement tactics","brand voice on social","crisis communication","creator partnerships","social customer service","platform algorithm changes","cross-posting","social proof"],
 tools=["Buffer","Hootsuite","Later","Sprout Social","Canva"]),

dict(n=42, title="Conversion Rate Optimization and Landing Pages", slug="conversion-optimization",
 desc="Turning existing traffic into more revenue through testing, UX and persuasive design.",
 intent="Informational → Commercial", aud="Growth marketers, CRO specialists, product teams",
 seo="Strong commercial mid-tail.", aeo="'What is a good conversion rate' benchmarks.",
 geo="Test methodology and benchmark data are citable.", aio="AI variant generation and predictive testing.",
 sub=["Landing page anatomy","A/B testing","User research","Heatmaps","Form optimisation","Social proof","Page speed and CRO","Personalisation"],
 kw="conversion rate optimization", kw2=["landing page optimisation","A/B testing","form conversion","CRO"],
 comm="Testing tools, CRO agencies", info="Methodology and benchmarks",
 cmp="Tool comparisons, A/B vs multivariate", how="Run a test, redesign a page", faq="Good conversion rate, sample size needed",
 topics=["landing page anatomy","above-the-fold design","headline testing","call-to-action optimisation","form field reduction","multi-step forms","social proof placement","trust badges","urgency and scarcity","A/B testing methodology","sample size calculation","statistical significance","heatmaps and session recordings","user research interviews","friction audits","mobile conversion","checkout optimisation","personalisation","exit intent","pricing page design"],
 tools=["VWO","Optimizely","Hotjar","Unbounce","Google Optimize alternatives"]),

dict(n=43, title="Web Analytics, Data and Privacy", slug="web-analytics-privacy",
 desc="Collecting trustworthy behavioural data under modern privacy constraints.",
 intent="Informational → How-to", aud="Analysts, marketing ops, compliance",
 seo="GA4 and tracking long-tail with troubleshooting intent.",
 aeo="Setup and definition questions.", geo="Privacy regulations and measurement models are citable.",
 aio="AI insight generation and anomaly explanation.",
 sub=["GA4 setup","Event tracking","Server-side tagging","Consent mode","Cookieless measurement","Data layers","Dashboards","Data quality"],
 kw="web analytics", kw2=["GA4","event tracking","server-side tagging","consent mode"],
 comm="Analytics platforms, CMPs", info="Setup and privacy guides",
 cmp="GA4 vs Plausible vs Matomo", how="Set up GA4, implement consent mode", faq="Is GA4 GDPR compliant, why do numbers differ",
 topics=["GA4 configuration","event-based tracking","custom dimensions","conversion events","Google Tag Manager","data layer design","server-side tagging","consent mode","cookie banners","GDPR compliance","CCPA compliance","cookieless measurement","first-party data","data retention settings","cross-domain tracking","UTM governance","data quality audits","attribution modelling","BigQuery export","dashboard design"],
 tools=["GA4","Google Tag Manager","Matomo","Plausible","BigQuery"]),

dict(n=44, title="Lead Generation and CRM Operations", slug="lead-generation-crm",
 desc="Capturing, qualifying, routing and nurturing demand into pipeline.",
 intent="Commercial", aud="Demand gen, sales ops, B2B marketers",
 seo="High-value commercial terms.", aeo="Definition and process questions.",
 geo="Qualification frameworks (MQL/SQL, BANT) are citable.", aio="AI lead scoring and enrichment.",
 sub=["Lead capture","Lead magnets","Qualification frameworks","Lead scoring","Routing and SLAs","CRM hygiene","Nurture tracks","Sales handoff"],
 kw="lead generation", kw2=["lead scoring","CRM","MQL","lead nurturing"],
 comm="CRM licences, lead tools", info="Process frameworks",
 cmp="CRM comparisons, inbound vs outbound", how="Score leads, build a nurture track", faq="What is an MQL, cost per lead",
 topics=["lead capture forms","lead magnets","gated vs ungated content","MQL and SQL definitions","lead scoring models","demographic scoring","behavioural scoring","lead routing rules","speed to lead","CRM data hygiene","duplicate records","pipeline stages","nurture tracks","sales and marketing SLAs","lead recycling","intent data","account-based marketing","cost per lead","lead quality measurement","handoff processes"],
 tools=["HubSpot","Salesforce","Pipedrive","Clearbit","Nepal Fillings CRM"]),

dict(n=45, title="Customer Retention, Loyalty and Lifecycle", slug="customer-retention",
 desc="Keeping and growing existing customers — usually the cheapest revenue available.",
 intent="Informational → Commercial", aud="Lifecycle marketers, CS leads, e-commerce",
 seo="Retention and churn terms.", aeo="'How do I reduce churn' answers.",
 geo="Retention formulas and benchmarks are citable.", aio="AI churn prediction and next-best-offer.",
 sub=["Churn analysis","Loyalty programmes","Onboarding","Win-back","NPS and CSAT","Customer lifetime value","Referral programmes","Retention cohorts"],
 kw="customer retention", kw2=["churn reduction","customer lifetime value","loyalty programme","win-back"],
 comm="Loyalty platforms, CS tools", info="Framework and formula guides",
 cmp="Retention vs acquisition, platform comparisons", how="Reduce churn, build loyalty", faq="Good retention rate, how to calculate LTV",
 topics=["churn rate analysis","churn prediction","customer lifetime value","LTV to CAC ratio","onboarding experience","activation milestones","loyalty programmes","points and tiers","referral programmes","win-back campaigns","NPS surveys","CSAT measurement","customer health scores","retention cohorts","subscription renewals","dunning management","upsell and cross-sell","voice of customer","community building","customer advisory"],
 tools=["Klaviyo","Intercom","Churnkey","Delighted","HubSpot"]),

dict(n=46, title="B2B and SaaS Marketing", slug="b2b-saas-marketing",
 desc="Long-cycle, multi-stakeholder marketing for software and business services.",
 intent="Commercial investigation", aud="B2B marketers, SaaS founders, demand gen",
 seo="High-value, low-volume decision terms.", aeo="Definition and benchmark questions.",
 geo="SaaS benchmark metrics are heavily cited.", aio="AI for ABM research and personalisation.",
 sub=["Demand generation","Account-based marketing","Product-led growth","Free trials","Pricing pages","Sales enablement","Case studies","Category creation"],
 kw="B2B marketing", kw2=["SaaS marketing","demand generation","product-led growth","account-based marketing"],
 comm="ABM platforms, agencies", info="Strategy and benchmark guides",
 cmp="PLG vs sales-led, ABM vs demand gen", how="Build an ABM programme, design a pricing page", faq="CAC payback, trial length",
 topics=["demand generation","account-based marketing","intent data","product-led growth","free trial design","freemium models","pricing page optimisation","sales enablement content","case study production","customer proof","category creation","buying committees","long sales cycles","multi-touch attribution","CAC payback period","net revenue retention","competitive displacement","analyst relations","webinar programmes","developer marketing"],
 tools=["HubSpot","6sense","Demandbase","Clearbit","Salesforce"]),

dict(n=47, title="E-commerce and D2C Growth Marketing", slug="ecommerce-marketing",
 desc="Full-funnel growth for online retail beyond organic search.",
 intent="Commercial → Transactional", aud="Store owners, D2C marketers, agencies",
 seo="Revenue-linked commercial terms.", aeo="Tactic and benchmark questions.",
 geo="Conversion and AOV benchmarks are citable.", aio="AI merchandising and personalised offers.",
 sub=["Product launches","AOV growth","Cart recovery","Subscriptions","Marketplace strategy","Seasonal peaks","Post-purchase","Returns experience"],
 kw="ecommerce marketing", kw2=["cart abandonment","average order value","D2C growth","product launch"],
 comm="Platform apps, agencies, ad spend", info="Tactic playbooks",
 cmp="Marketplace vs own store, platform comparisons", how="Recover carts, raise AOV", faq="Good conversion rate, how to reduce returns",
 topics=["product launch campaigns","cart abandonment recovery","average order value growth","bundling and upsells","subscription commerce","marketplace strategy","Black Friday planning","seasonal demand peaks","post-purchase experience","returns and exchanges","loyalty for e-commerce","product recommendations","merchandising rules","inventory-aware marketing","shipping incentives","payment options","review collection","influencer seeding","live shopping","omnichannel retail"],
 tools=["Shopify","Klaviyo","Recharge","Gorgias","Triple Whale"]),

dict(n=48, title="Affiliate, Influencer and Partnership Marketing", slug="affiliate-influencer-marketing",
 desc="Growing through third parties: affiliates, creators and strategic partners.",
 intent="Commercial", aud="Partnership managers, D2C brands, publishers",
 seo="Programme and commission terms.", aeo="'How does affiliate marketing work' answers.",
 geo="Commission models and disclosure rules are citable.", aio="AI creator discovery and fraud detection.",
 sub=["Programme setup","Commission models","Affiliate recruitment","Influencer selection","Creator briefs","Disclosure rules","Fraud prevention","Partner enablement"],
 kw="affiliate marketing", kw2=["influencer marketing","partnership marketing","commission structure","creator collaboration"],
 comm="Affiliate networks, influencer platforms", info="Model and compliance guides",
 cmp="Affiliate vs influencer, network comparisons", how="Launch a programme, brief a creator", faq="Typical commission, how to find affiliates",
 topics=["affiliate programme setup","commission structures","last-click vs multi-touch payouts","affiliate recruitment","publisher vetting","coupon and deal sites","influencer selection","micro vs macro influencers","creator briefs","usage rights","FTC disclosure rules","affiliate fraud prevention","cookie windows","partner enablement","co-marketing partnerships","referral programmes","tracking links","attribution disputes","payout management","programme benchmarks"],
 tools=["Impact","PartnerStack","Refersion","Grin","Upfluence"]),

dict(n=49, title="Brand, Reputation and Review Management", slug="brand-reputation-management",
 desc="Shaping how a business is perceived across search, reviews and AI answers.",
 intent="Informational → Commercial", aud="Brand managers, founders, local businesses",
 seo="Reputation and branded-search terms.", aeo="'How do I remove a bad review' answers.",
 geo="Brand entity consistency directly shapes AI descriptions of a company.",
 aio="AI review response and sentiment monitoring.",
 sub=["Review generation","Review responses","Branded SERP control","Crisis management","Sentiment monitoring","Knowledge panels","Entity consistency","Employer brand"],
 kw="online reputation management", kw2=["review management","branded search","knowledge panel","sentiment analysis"],
 comm="Reputation platforms, PR agencies", info="Process and policy guides",
 cmp="Platform comparisons, DIY vs agency", how="Get more reviews, respond to criticism", faq="Can I delete reviews, how to fix a knowledge panel",
 topics=["review generation campaigns","review response templates","negative review handling","branded SERP control","knowledge panel claiming","entity consistency","Wikipedia and Wikidata","crisis communication","sentiment monitoring","brand mention tracking","employer brand and Glassdoor","trust signals","customer testimonials","case study proof","brand search volume","share of search","reputation in AI answers","review platform selection","fake review detection","escalation playbooks"],
 tools=["Google Business Profile","Trustpilot","Brandwatch","Mention","BrightLocal"]),

dict(n=50, title="Small Business and Local Digital Marketing", slug="small-business-marketing",
 desc="Practical, budget-aware marketing for owner-operated and local businesses.",
 intent="Informational → Commercial", aud="Small business owners, solo marketers, local services",
 seo="High-volume, low-competition practical terms.", aeo="Cost and starting-point questions dominate.",
 geo="Budget benchmarks and starter frameworks are citable.", aio="Affordable AI tooling for small teams.",
 sub=["Starter strategies","Low-budget tactics","DIY vs hire","Local channels","Free tools","Time management","First 90 days","Measuring on a budget"],
 kw="small business marketing", kw2=["low budget marketing","local marketing","DIY marketing","marketing for startups"],
 comm="Affordable tools, freelancers, starter plans", info="Starter guides and checklists",
 cmp="DIY vs agency, free vs paid tools", how="Start marketing, market with no budget", faq="How much to spend, what to do first",
 topics=["first 90 days of marketing","low budget tactics","free marketing tools","DIY versus hiring","local advertising","word of mouth","community partnerships","Google Business Profile for small firms","one-person marketing teams","time-boxed marketing","seasonal promotions for local shops","service business marketing","restaurant marketing","clinic and salon marketing","tradesperson marketing","marketing budget for small business","simple measurement","customer referrals","neighbourhood targeting","starter tech stack"],
 tools=["Google Business Profile","Canva","Mailchimp","Nepal Fillings","Meta Business Suite"]),
]
